kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kogito-monitoring
rules:
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
  - verbs:
      - '*'
    apiGroups:
      - integreatly.org
    resources:
      - grafanadashboards