---
# Implement your Pre Workload deployment tasks here
- name: Fail if user count incorrect
  fail:
    msg: User count end({{ user_count_end }}) <= user count start ({{ user_count_start }})
  when: user_count_end|int <= user_count_start|int

- name: Ensure tmp directory exists
  file:
    path: "{{ tmp_dir }}"
    state: directory

# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."