---
- name: set namespace
  set_fact:
    _namespace: "codeready-workspaces"

- name: Delete Che Cluster
  k8s:
    state: absent
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('template', role_path ~ '/files/codeready-workspaces/cluster.yml' ) | from_yaml }}"

- name: Delete operator
  k8s:
    state: absent
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/codeready-workspaces/operator.yml' ) | from_yaml }}"

- name: Delete OperatorGroup for the operators
  k8s:
    state: absent
    definition: "{{ lookup('template', role_path ~ '/templates/olm-operatorgroup/single-namespace.j2' ) | from_yaml }}"

- name: Delete namespace for {{ _namespace }}
  k8s:
    state: absent
    definition: "{{ lookup('template', role_path ~ '/templates/namespace-without-requester.j2' ) | from_yaml }}"
  vars:
    _description: "Codeready Workspaces"
