---

# Implement your Workload removal tasks here
- name: remove projects loop
  include_tasks: remove_workload_per_project.yml
  loop: "{{ range(user_count_start|int, user_count_end|int)|list }}"
  loop_control:
    loop_var: user_num

- name: remove monitoring per cluster
  include_tasks: remove_workload_per_cluster_monitoring.yml

- name: remove Kogito per cluster
  include_tasks: remove_workload_per_cluster_kogito.yml

- name: remove Infinispan per cluster
  include_tasks: remove_workload_per_cluster_infinispan.yml

- name: remove Strimzi per cluster
  include_tasks: remove_workload_per_cluster_strimzi.yml

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
