---
- name: set namespace
  set_fact:
    _namespace: "{{ namespace_prefix }}{{ user_num }}"

- name: "remove monitoring workload for user user{{ user_num }}"
  include_tasks: remove_workload_per_project_monitoring.yml

- name: "remove Infinispan cluster workload for user user{{ user_num }}"
  include_tasks: remove_workload_per_project_infinispan_cluster.yml

- name: "remove Kafka cluster workload for user user{{ user_num }}"
  include_tasks: remove_workload_per_project_kafka_cluster.yml

- name: "remove Infinispan workload for user user{{ user_num }}"
  include_tasks: remove_workload_per_project_infinispan.yml

- name: "remove Strimzi workload for user user{{ user_num }}"
  include_tasks: remove_workload_per_project_strimzi.yml

- name: "remove Kogito workload for user user{{ user_num }}"
  include_tasks: remove_workload_per_project_kogito.yml

- name: delete {{ _namespace }} project
  k8s:
    state: absent
    definition: "{{ lookup('template', role_path ~ '/templates/namespace.j2' ) | from_yaml }}"
