---

- name: "remove monitoring key label from namespace {{ _namespace }}"
  shell: >
    oc label namespace {{ _namespace }} monitoring-key- 

- name: "remove get namespaces privilege from user{{ user_num }}"
  k8s:
    state: absent
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/get-namespaces-clusterrolebinding.yml' ) | from_yaml }}"

- name: "delete application monitoring cr for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/application-monitoring-cr.yml' ) | from_yaml }}"

- name: "delete application monitoring operator deployment for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/application-monitoring-operator-deployment.yml' ) | from_yaml }}"

- name: "delete application monitoring operator role binding for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/application-monitoring-operator-rolebinding.yml' ) | from_yaml }}"

- name: "delete application monitoring operator role for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/monitoring/application-monitoring-operator-role.yml' ) | from_yaml }}"

- name: "delete application monitoring operator service account for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('file', role_path ~ '/files/monitoring/application-monitoring-operator-serviceaccount.yml' ) | from_yaml }}"

- name: "delete Prometheus alertmanager rolebinding for user user{{ user_num }}"
  k8s:
    state: absent    
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/alertmanager-monitoring-clusterrolebinding.yml' ) | from_yaml }}"

- name: "delete Prometheus application monitoring rolebinding for user user{{ user_num }}"
  k8s:
    state: absent    
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/prometheus-monitoring-clusterrolebinding.yml' ) | from_yaml }}"

- name: "delete Prometheus operator rolebinding for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/prometheus-operator-clusterrolebinding.yml' ) | from_yaml }}"

- name: "delete Grafana proxy rolebinding for user user{{ user_num }}"
  k8s:
    state: absent  
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/grafana-proxy-clusterrolebinding.yml' ) | from_yaml }}"

- name: "delete Grafana operator rolebinding for user user{{ user_num }}"
  k8s:
    state: absent
    namespace: "{{ _namespace }}"    
    definition: "{{ lookup('template', role_path ~ '/templates/monitoring/grafana-operator-rolebinding.yml' ) | from_yaml }}"
