---

- name: Strimzi for cluster
  include_tasks: workload_per_cluster_strimzi.yml

- name: Infinispan workload for cluster
  include_tasks: workload_per_cluster_infinispan.yml

- name: Kogito workload for cluster
  include_tasks: workload_per_cluster_kogito.yml

- name: Monitoring workload for cluster
  include_tasks: workload_per_cluster_monitoring.yml