---
# Implement your Post Workload deployment tasks here
# --------------------------------------------------

- name: Get console route
  k8s_info:
    kind: Route
    api_version: route.openshift.io/v1
    namespace: openshift-console
    name: console
  register: r_console_route

- name: Set webconsole address
  set_fact:
    webconsole: "https://{{ r_console_route.resources[0].spec.host }}"

- name: Get API for command line
  command: oc whoami --show-server
  register: r_showserver

- name: Print Overview
  agnosticd_user_info:
    msg: "{{ item }}"
  with_items:
    - ""
    - '**********'
    - 'IMPORTANT: You cannot SSH into the shared cluster.'
    - Please refer to the demo or lab instructions in order
    - to get the steps on how to access the environment properly.
    - '**********'
    - ""
    - "Openshift Master Console: {{ webconsole }}"
    - "Openshift API for command line 'oc' client: {{ r_showserver.stdout | trim }}"

# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload tasks completed successfully."
  when:
  - not silent|bool
  - not workload_shared_deployment|default(False)

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: post_workload tasks complete
  debug:
    msg: "Post-Software checks completed successfully"
  when:
  - not silent|bool
  - workload_shared_deployment|default(False)
