---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-operator
subjects:
  - kind: ServiceAccount
    name: grafana-operator
    namespace: "{{ _namespace }}"
