---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-application-monitoring-operator-user{{ user_num }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-application-monitoring-operator
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: "{{ _namespace }}"