---

# Implement your Workload removal tasks here

- name: define ocp projects
  set_fact:
    ocp_project_amq_streams: "amq-streams-{{ guid }}"
    ocp_project_kafka_security: "kafka-security-{{ guid }}"

- name: amq streams tasks
  include_tasks: remove_workload_amq_streams.yml

- name: remove user projects
  k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
  loop:
    - "{{ ocp_project_amq_streams }}"
    - "{{ ocp_project_kafka_security }}"

- name: remove user quota - clusterresourcequota
  k8s:
    state: absent
    name: "clusterquota-{{ ocp_username }}-{{ guid }}"
    kind: ClusterResourceQuota
    api_version: quota.openshift.io/v1

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
