---
# Implement your Workload deployment tasks here

- name: define user projects
  set_fact:
    ocp_project_amq_streams: "amq-streams-{{ guid }}"
    ocp_project_kafka_security: "kafka-security-{{ guid }}"

- name: create projects for user
  k8s:
    state: present
    definition: "{{ lookup('template', role_path ~ '/templates/namespace.j2' ) | from_yaml }}"
  vars:
    ocp_project: "{{ item }}"
  loop:
    - "{{ ocp_project_amq_streams }}"
    - "{{ ocp_project_kafka_security }}"

- name: give user admin privileges in namespace
  k8s:
    state: present
    namespace: "{{ item }}"
    definition: "{{ lookup('template', role_path ~ '/templates/namespace-admin-rb.j2' ) | from_yaml }}"
  loop:
    - "{{ ocp_project_amq_streams }}"
    - "{{ ocp_project_kafka_security }}"

- name: delete existing limitrange
  k8s:
    state: absent
    namespace: "{{ item }}"
    name: "{{ item }}-core-resource-limits"
    api_version: v1
    kind: LimitRange
  loop:
    - "{{ ocp_project_amq_streams }}"
    - "{{ ocp_project_kafka_security }}"

- name: create limitrange in namespace
  k8s:
    state: present
    namespace: "{{ item }}"
    definition: "{{ lookup('template', role_path ~ '/templates/limitrange.j2' ) | from_yaml }}"
  vars:
    ocp_project: "{{ item }}"
  loop:
    - "{{ ocp_project_amq_streams }}"
    - "{{ ocp_project_kafka_security }}"

- name: amq streams tasks
  include_tasks: workload_amq_streams.yml

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
